- name: Add ZeroTier PGP key
  apt_key:
    url: "{{ zerotier_gpg_url }}"

- name: Check if Ubuntu release has dedicated repo
  uri:
    url: "{{ zerotier_download_base_url }}/debian/{{ zerotier_deb_release_repo }}"
  failed_when: false
  when:
    - ansible_facts['distribution'] == "Ubuntu"
  register: release_repo

- name: Print distribution version
  ansible.builtin.debug:
    msg: Distribution is {{ ansible_facts['distribution'] }}, Major version is {{ ansible_facts['distribution_major_version'] }}

- block:
  - name: Overwrite Ubuntu release repo name to bionic for 18.x
    set_fact:
      zerotier_deb_release_repo: bionic

  - name: Re-gather facts
    setup: ~

  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_major_version'] == "18"
    - release_repo.status == 404

# a kludge needed cause there's no repo for ubuntu focal yet
- block:
  - name: Overwrite Ubuntu release repo name to disco for Ubuntu and Linux Mint 19.x and 20.x
    set_fact:
      zerotier_deb_release_repo: disco

  - name: Re-gather facts
    setup: ~

  when:
    - ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Linux Mint"
    - ansible_facts['distribution_major_version'] == "19" or ansible_facts['distribution_major_version'] == "20"
 #   - release_repo.status == 404

- name: Add ZeroTier APT repository
  apt_repository:
    repo: deb {{ zerotier_download_base_url }}/debian/{{ zerotier_deb_release_repo }} {{ zerotier_deb_release_repo }} main
    filename: zerotier
  register: zerotier_repo
